task_manager/labels/urls.py
from django.urls import path
from .views import (
    LabelListView,
    LabelCreateView,
    LabelUpdateView,
    LabelDeleteView
)

app_name = 'labels'

urlpatterns = [
    path('', LabelListView.as_view(), name='list'),
    path('create/', LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', LabelDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path
from .views import (
    TaskListView,
    TaskCreateView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView
)

app_name = 'tasks'

urlpatterns = [
    path('create/', TaskCreateView.as_view(), name='create'),
    path('', TaskListView.as_view(), name='list'),
    path('<int:pk>/', TaskDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, LoginView, LogoutView  # error


urlpatterns = [
    path("", HomeView.as_view(), name='index'),
    path("admin/", admin.site.urls),
    path("users/", include('task_manager.users.urls', namespace='users')),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path(
        'statuses/',
        include('task_manager.statuses.urls', namespace='statuses')
    ),
    path('labels/', include('task_manager.labels.urls', namespace='labels')),
    path('tasks/', include('task_manager.tasks.urls', namespace='tasks')),
#   path('error/', error, name='error'),
]

task_manager/users/urls.py
from django.urls import path
from task_manager.users.views import (
    UserCreateView,
    UserListView,
    UserUpdateView,
    UserDeleteView
)

app_name = 'users'

urlpatterns = [
    path("create/", UserCreateView.as_view(), name="create"),
    path("", UserListView.as_view(), name="list"),
    path("<int:pk>/update/", UserUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", UserDeleteView.as_view(), name="delete")
]

task_manager/labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Имя')
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=_('Дата создания'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Метка")
        verbose_name_plural = _("Метки")

task_manager/tasks/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from task_manager.statuses.models import Status
from task_manager.users.models import User
from task_manager.labels.models import Label


class Task(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
        verbose_name=_('Имя')
    )

    description = models.TextField(
        blank=True,
        verbose_name=_('Описание')
    )

    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        verbose_name=_('Статус')
    )

    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='authored_tasks',
        verbose_name=_('Автор')
    )

    executor = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='executed_tasks',
        null=True,
        blank=True,
        verbose_name=_('Исполнитель')
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Дата создания')
    )

    labels = models.ManyToManyField(
        Label,
        related_name='tasks',
        blank=True,
        verbose_name=_('Метки')
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Задача')
        verbose_name_plural = _('Задачи')

task_manager/labels/forms.py
from django import forms
from .models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ['name']
        labels = {
            'name': 'Имя'
        }

task_manager/statuses/forms.py
from django import forms
from .models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']
        labels = {'name': 'Имя', }

task_manager/tasks/forms.py
from django import forms
from .models import Task
from task_manager.statuses.models import Status
from task_manager.users.models import User
from django.utils.translation import gettext_lazy as _


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']
        labels = {
            'name': _('Имя'),
            'description': _('Описание'),
            'status': _('Статус'),
            'executor': _('Исполнитель'),
            'labels': _('Метки'),
        }

        widgets = {
            'labels': forms.SelectMultiple(),
        }

        def __init__(self, *args, **kwargs):
            self.user = kwargs.pop('user', None)
            super().__init__(*args, **kwargs)
            self.fields['executor'].queryset = User.objects.all()
            self.fields['status'].queryset = Status.objects.all()

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        ]
        labels = {
            'username': 'Имя пользователя',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'password1': 'Пароль',  # NOSONAR
            'password2': 'Подтверждение пароля',  # NOSONAR
        }


class UserUpdateForm(forms.ModelForm):
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput,
        required=False
    )
    password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput,
        required=False
    )

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        ]

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Введенные пароли не совпадают")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data["password1"]
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Имя пользователя",
        widget=forms.TextInput
    )
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput
    )

task_manager/labels/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Label
from .forms import LabelForm
from django.contrib import messages
from django.utils.translation import gettext_lazy as _


class LabelListView(LoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/list.html'
    context_object_name = "labels"


class LabelCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/create.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('Метка успешно создана')


class LabelUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/update.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('Метка успешно изменена')


class LabelDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Label
    template_name = 'labels/delete.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('Метка успешно удалена')
    error_message = _('Невозможно удалить метку, потому что она используется')

    def post(self, request, *args, **kwargs):
        label = self.get_object()

        if label.tasks.exists():
            messages.error(request, self.error_message)
            return redirect(self.success_url)
        try:
            label.delete()
            messages.success(request, self.success_message)
            return redirect(self.success_url)
        except Exception as e:
            messages.error(request, str(e))
            return redirect(self.success_url)

task_manager/statuses/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from .models import Status
from .forms import StatusForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import ProtectedError


class StatusListView(LoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/list.html'
    context_object_name = 'statuses'


class StatusCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/create.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _('Статус успешно создан')


class StatusUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/update.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _('Статус успешно изменен')


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'statuses/delete.html'
    success_message = _('Статус успешно удален')
    success_url = reverse_lazy('statuses:list')
    error_message = _('Невозможно удалить статус, потому что он используется')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            messages.success(request, self.success_message)
            return redirect(self.success_url)
        except ProtectedError:
            messages.error(request, self.error_message)
            return redirect(self.success_url)

task_manager/tasks/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, CreateView, UpdateView, DeleteView, DetailView
)
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from .models import Task
from task_manager.statuses.models import Status
from task_manager.labels.models import Label
from task_manager.users.models import User
from .forms import TaskForm
from .filters import TaskFilter


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'tasks/list.html'
    context_object_name = 'tasks'
    filterset_class = TaskFilter

    def get_queryset(self):
        self.filterset = self.filterset_class(
            self.request.GET,
            queryset=super().get_queryset(),
            request=self.request
        )
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        context['statuses'] = Status.objects.all()
        context['users'] = User.objects.all()
        context['labels'] = Label.objects.all()
        return context


class TaskCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/create.html'
    success_url = reverse_lazy('tasks:list')
    success_message = _('Задача успешно создана')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/update.html'
    success_url = reverse_lazy('tasks:list')
    success_message = _('Задача успешно изменена')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/detail.html'
    context_object_name = 'task'


class TaskDeleteView(LoginRequiredMixin,
                     UserPassesTestMixin,
                     SuccessMessageMixin,
                     DeleteView
                     ):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy('tasks:list')
    success_message = _('Задача успешно удалена')

    def test_func(self):
        task = self.get_object()
        return task.author == self.request.user

    def handle_no_permission(self):
        messages.error(self.request, _('Задачу может удалить только ее автор'))
        return redirect(self.success_url)

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, self.success_message)
        return response

task_manager/users/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import User
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from .forms import UserRegisterForm, UserUpdateForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages


class UserListView(ListView):
    model = User
    template_name = 'users/list.html'
    context_object_name = 'users'


class UserCreateView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/create.html'
    success_url = reverse_lazy('login')
    success_message = _('Пользователь успешно зарегистрирован')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/update.html'
    success_url = reverse_lazy('users:list')
    success_message = _('Пользователь успешно изменен')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object != self.request.user:
            messages.error(
                request,
                _('У вас нет прав для изменения другого пользователя.')
            )
            return redirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)


class UserDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = User
    template_name = 'users/delete.html'
    success_url = reverse_lazy('users:list')
    success_message = _('Пользователь успешно удален')

    def get(self, request, *args, **kwargs):
        user_to_delete = self.get_object()
        current_user = request.user

        if user_to_delete != current_user:
            messages.error(
                request,
                _('У вас нет прав для изменения другого пользователя.')
            )
            return redirect(self.success_url)
        if (
            hasattr(user_to_delete, 'authored_tasks') and
            user_to_delete.authored_tasks.exists()
        ):
            messages.error(
                request,
                _('Невозможно удалить пользователя, потому что'
                  'он используется в задачах')
            )
            return redirect(self.success_url)
        return super().get(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return response

task_manager/views.py
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages


class HomeView(TemplateView):
    template_name = "index.html"


class LoginView(SuccessMessageMixin, LoginView):
    template_name = 'users/login.html'
    success_message = "Вы залогинены"
    next_page = reverse_lazy('index')


class LogoutView(SuccessMessageMixin, LogoutView):
    next_page = reverse_lazy('index')
    success_message = "Вы разлогинены"

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, self.success_message)
        return super().dispatch(request, *args, **kwargs)
# Проверка rollbar
# def error(request):
#    division_by_zero = 1 / 0
#    return HttpResponse("You shouldn't be seeing this")

task_manager/templates/tasks/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block bootstrap5_content %}
<h1 class="my-4"></h1>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" value="{{ Создать задачу }}">
</form>
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block bootstrap5_content %}
<div class="container wrapper flex-grow-1">
  <h1 class="my-4">{% translate "Удаление задачи" %}</h1>
  
  <form method="post">
    {% csrf_token %}
    <p>{% translate "Вы уверены, что хотите удалить" %} {{ task.name }}?</p>
    <button type="submit" class="btn btn-danger">{% translate "Да, удалить" %}</button>
  </form>
</div>
{% endblock %}

task_manager/templates/tasks/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block bootstrap5_content %}
<div class="container wrapper flex-grow-1">
  <h1 class="my-4">{% translate "Просмотр задачи" %}</h1>
  
  <div class="card">
    <div class="card-header bg-secondary text-white">
      <h2>{{ task.name }}</h2>
    </div>
    <div class="card-body bg-light">
      <p>{{ task.description }}</p>
      <hr>
      <div class="container">
        <div class="row p-1">
          <div class="col">{% translate "Автор" %}</div>
          <div class="col">{{ task.author }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% translate "Исполнитель" %}</div>
          <div class="col">{{ task.executor|default:"" }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% translate "Статус" %}</div>
          <div class="col">{{ task.status }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% translate "Дата создания" %}</div>
          <div class="col">{{ task.created_at|date:"d.m.Y H:i" }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% translate "Метки" %}</div>
          <div class="col">
            <ul>
              {% for label in task.labels.all %}
              <li>{{ label.name }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/tasks/list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block bootstrap5_content %}
  <h1 class="my-4">{% translate "Задачи" %}</h1>
  
  <a href="{% url 'tasks:create' %}" class="btn btn-primary mb-3">
    {% translate "Создать задачу" %}
  </a>

  <div class="card mb-3">
    <div class="card-body bg-light">
      <form method="get" class="form-inline">

        <div class="mb-3">
          <label for="id_status" class="form-label">{% translate "Статус" %}</label>
          <select name="status" id="id_status" class="form-select">
            <option value="">---------</option>
            {% for status in statuses %}
              <option value="{{ status.id }}" 
                {% if filter.form.status.value == status.id|stringformat:"s" %}selected{% endif %}>
                {{ status.name }}
              </option>
            {% endfor %}
          </select>
        </div>
        
        <div class="mb-3">
          <label for="id_executor" class="form-label">{% translate "Исполнитель" %}</label>
          {{ filter.form.executor }}
        </div>
        
        <div class="mb-3">
          <label for="id_labels" class="form-label">{% translate "Метка" %}</label>
          {{ filter.form.labels }}
        </div>
        
        <div class="mb-3">
          <div class="form-check mt-4">
            {{ filter.form.self_tasks }}
            <label class="form-check-label" for="{{ filter.form.self_tasks.id_for_label }}">
              {% translate "Только свои задачи" %}
            </label>
          </div>
        </div>
        
        <button type="submit" class="btn btn-primary">{% translate "Показать" %}</button>
      </form>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>{% translate "Имя" %}</th>
        <th>{% translate "Статус" %}</th>
        <th>{% translate "Автор" %}</th>
        <th>{% translate "Исполнитель" %}</th>
        <th>{% translate "Дата создания" %}</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      {% for task in tasks %}
      <tr>
        <td>{{ task.id }}</td>
        <td><a href="{% url 'tasks:detail' task.id %}">{{ task.name }}</a></td>
        <td>{{ task.status }}</td>
        <td>{{ task.author }}</td>
        <td>{{ task.executor|default_if_none:"" }}</td>
        <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
        <td>
          <a href="{% url 'tasks:update' task.id %}">{% translate "Изменить" %}</a>
          <br>
          <a href="{% url 'tasks:delete' task.id %}">{% translate "Удалить" %}</a>
        </td>
      </tr>
      {% empty %}
        <tr></tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

task_manager/templates/tasks/update.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block bootstrap5_content %}
<h1 class="my-4">{% translate 'Изменение задачи' %}</h1>

<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">{% translate "Изменить" %}</button>
</form>
{% endblock %}